name: CI

on:
    push:
      branches: [ "master" ]


permissions:
    contents: read

jobs:
    run_tests:

        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4
        
          - name: Set up python 3.12
            uses: actions/setup-python@v3
            with:
                python-version: "3.12"
            
          - name: Set up make
            run: |
                sudo apt update
                sudo apt install -y make
          - name: Run tests
            run: |
                make test

