name: SSH test

on:
  workflow_dispatch:

permissions:
    contents: read
    
jobs:
    deploy_application:
        name: Deploy application on the remote server
        runs-on: ubuntu-latest

        steps:
            # - name: executing remote ssh commands using password
            #   uses: appleboy/ssh-action@v1.2.0
            #   with:
            #       host: direct.labs.play-with-docker.com
            #       username: ip172-18-0-6-ct84352im2rg00cta2u0
            #       # password: ${{ secrets.PASSWORD }}
            #       port: 22
            #       script: whoami
            # - name: executing remote ssh commands using password
            #   uses: appleboy/ssh-action@v1.2.0
            #   with:
            #       host: ${{ secrets.HOST }}
            #       username: linuxserver.io
            #       password: ${{ secrets.PASSWORD }}
            #       port: ${{ secrets.PORT }}
            #       script: whoami

          - name: Log into the server via SSH and deploy image
            run: |
                echo "${{ secrets.SELECTEL_PRIVATE_SSH_KEY }}" > ~/.ssh/selectel
                ssh -i ~/.ssh/selectel -o StrictHostKeyChecking=no root@${{ secrets.SELECTEL_SERVER_IP }} "whoami > ~/whoami"
