name: SSH test

on:
  workflow_dispatch:

permissions:
    contents: read
    
jobs:
    deploy_application:
        name: Deploy application on the remote server
        runs-on: ubuntu-latest

        steps:
          - name: Log into the server via SSH and deploy image
            run: |
                ssh -o StrictHostKeyChecking=no ip172-18-0-6-ct84352im2rg00cta2u0@direct.labs.play-with-docker.com "whoami"
